default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: postgres
  password: password
  host: db
development:
  <<: *default
  database: api_development_2


test:
  <<: *default
  database: api_test_2


production:
  <<: *default
  database: api_production_2
  username: api
  password: <%= ENV["API_DATABASE_PASSWORD"] %>
